export const BOARD_X_MAX = 6;
export const BOARD_Y_MAX = 6;

export enum ORIENTATION {
  NORTH = 'NORTH',
  SOUTH = 'SOUTH',
  EAST = 'EAST',
  WEST = 'WEST',
}

export const DIRECTIONS = [
  ORIENTATION.EAST,
  ORIENTATION.NORTH,
  ORIENTATION.WEST,
  ORIENTATION.SOUTH,
];
